version: '3.1'
services:
    frontend:
        image: ${{ env.REGISTRY }}/raphaelabl/deploy-angular
        container_name: angular-frontend
        ports:
          - "80:80"
    backend:
       image: raphaelabl/deploy-quarkus
       user: root
       container_name: backend-quarkus
       environment:
          
      ports:
          - "8080:8080"

