## A basic GitHub Actions workflow for your Quarkus application.
 
name: CI build
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io

jobs:
  build-frontend:
    name: build-frontend-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./deploy/src/main/frontend/
          file: ./deploy/src/main/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/deploy-angular:latest
          build-args: |
            configuration=production
          cache-from: type=registry,ref=${{ env.REGISTRY }}/deploy-angular:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/deploy-angular:buildcache,mode=max

  build-backend:
    name: build-backend-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./deploy/
        run: |
          chmod +x ./mvnw
          ./mvnw package -Dmaven.test.skip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./deploy/
          file: ./deploy/src/main/docker/Dockerfile.jvm
          push: true
          tags: ${{ env.REGISTRY }}/deploy-quarkus:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/deploy-quarkus:latest
          cache-to: type=inline


